// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGSzbnyyyb00sq60YtL75Qg6SlF4hyfw',
    appId: '1:146906581981:web:306d7620ecda3f09cb4434',
    messagingSenderId: '146906581981',
    projectId: 'crudnotes-1ebb6',
    authDomain: 'crudnotes-1ebb6.firebaseapp.com',
    storageBucket: 'crudnotes-1ebb6.firebasestorage.app',
    measurementId: 'G-Y0QY8WGV59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-hdKRPOtsSUjvsYUNArJfbLwjrZGRME',
    appId: '1:146906581981:android:9424226358604060cb4434',
    messagingSenderId: '146906581981',
    projectId: 'crudnotes-1ebb6',
    storageBucket: 'crudnotes-1ebb6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxGSzbnyyyb00sq60YtL75Qg6SlF4hyfw',
    appId: '1:146906581981:web:3b08d543adeb4916cb4434',
    messagingSenderId: '146906581981',
    projectId: 'crudnotes-1ebb6',
    authDomain: 'crudnotes-1ebb6.firebaseapp.com',
    storageBucket: 'crudnotes-1ebb6.firebasestorage.app',
    measurementId: 'G-G29YWDTE6D',
  );
}
